// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProjectTool1;

internal sealed partial class Vsix
{
    public const string Id = "VSIXProjectTool1.23831ad0-420b-4509-93da-b3e8ff67efe5";
    public const string Name = "VSIXProjectTool1";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Taner Saydam";
    public const string Tags = "";
}
