// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject1;

internal sealed partial class Vsix
{
    public const string Id = "VSIXProject1.54f585ef-fb30-44a2-9d89-3aed771f7293";
    public const string Name = "VSIXProject1";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Taner Saydam";
    public const string Tags = "";
}
