@eHospitalServer.WebAPI_HostAddress = http://localhost:5019

GET https://localhost:7169/api/Auth/Get
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMzOTY4MDFjLTI5ODgtNDY0Zi1hZmUyLWY5ZTg4ZDRiZTIwMCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJUYW5lciBTYXlkYW0iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBhZG1pbi5jb20iLCJVc2VyTmFtZSI6ImFkbWluIiwibmJmIjoxNzA5MDYwMzQyLCJleHAiOjE3MDkwNjM5NDIsImlzcyI6IlRhbmVyIFNheWRhbSIsImF1ZCI6IsOWxJ9yZW5jaWxlcmltIn0.bgVhAFeD8pvC_70JodVrtIfJqBhOdqVUrZgTZbmy0sBcUyeKZnmGEMSczAbKy5kh0IjVlTbbQJtaKS74H9OV0g

###
